"use client";

import * as React from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import {
  ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, Check,
  ChevronDown, CircleCheck, Gauge, Headphones, Layers3, LockKeyhole,
  MessageSquareText, Radio, ShieldCheck, Sparkles, Target, Users, Workflow,
} from "lucide-react";
import { DemoLink, ScheduleButton } from "@/components/tracked-actions";
import { Reveal } from "@/components/ui/reveal";
import { Eyebrow, Section, SectionHeading } from "@/components/ui/primitives";
import {
  CallScorePanel, CoachPanel, DealScorePanel, LiveCallDemo, ManagerDashboard,
  PlaybookPanel, ReportPreview, SystemFlow, ZeroPromptComparison,
} from "@/components/product-ui";
import { track } from "@/lib/analytics";

const pillars = [
  { icon: Radio, title: "Morubi Live", text: "Orientação contextual enquanto a conversa acontece.", href: "/live", status: "Prévia" },
  { icon: BrainCircuit, title: "Intelligence", text: "Cada call vira evidência, score e aprendizado.", href: "/intelligence", status: "Prévia" },
  { icon: Target, title: "Coach", text: "Desenvolvimento baseado no comportamento real.", href: "/coach", status: "Roadmap" },
  { icon: BarChart3, title: "Manager", text: "Padrões e gargalos em toda a operação.", href: "/manager", status: "Prévia" },
] as const;

export function NewHero() {
  return <section className="relative overflow-hidden pb-20 pt-32 sm:pb-28 sm:pt-40">
    <div className="pointer-events-none absolute inset-0 bg-grid opacity-60" />
    <div className="aurora pointer-events-none absolute left-1/2 top-[-300px] h-[720px] w-[1000px] -translate-x-1/2 rounded-full" />
    <div className="relative mx-auto max-w-8xl px-5 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl text-center">
        <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:.6}}><Eyebrow>Inteligência comercial em tempo real</Eyebrow></motion.div>
        <motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.75,delay:.06}} className="mx-auto mt-6 max-w-[920px] text-balance text-[38px] font-semibold leading-[1.04] tracking-[-.04em] text-foreground sm:text-6xl sm:tracking-[-.045em] lg:text-[72px]">Seu melhor gerente comercial não consegue estar em todas as calls. <span className="text-gradient-accent">A Morubi consegue.</span></motion.h1>
        <motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.75,delay:.14}} className="mx-auto mt-6 max-w-2xl text-pretty text-[16px] leading-7 text-muted sm:text-[18px]">Acompanha cada vendedor, identifica momentos críticos e transforma cada conversa em inteligência para melhorar toda a operação comercial.</motion.p>
        <motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.75,delay:.22}} className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><DemoLink/><ScheduleButton/></motion.div>
        <motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.6,delay:.4}} className="mt-5 text-xs text-muted">Sem cartão de crédito <span aria-hidden="true">•</span> Setup personalizado <span aria-hidden="true">•</span> Playbook da sua empresa</motion.p>
      </div>
      <motion.div initial={{opacity:0,y:24,scale:.985}} animate={{opacity:1,y:0,scale:1}} transition={{duration:1,delay:.28}} className="relative mx-auto mt-14 max-w-5xl"><div className="pointer-events-none absolute -inset-10 bg-accent/[.08] blur-[100px]"/><LiveCallDemo/></motion.div>
      <div className="mx-auto mt-10 grid max-w-5xl grid-cols-2 gap-2 lg:grid-cols-4">{pillars.map((p,i)=><Reveal key={p.title} delay={i*.06}><Link href={p.href} className="group block h-full rounded-xl border border-white/[.07] bg-white/[.018] p-4 transition hover:border-accent/25 hover:bg-white/[.03]"><div className="flex items-center justify-between"><p.icon size={15} className="text-accent"/><span className="text-[9px] uppercase tracking-wider text-muted">{p.status}</span></div><p className="mt-3 text-sm font-medium">{p.title}</p><p className="mt-1 text-xs leading-5 text-muted">{p.text}</p></Link></Reveal>)}</div>
    </div>
  </section>
}

export function LearningTransition(){return <Section className="border-y border-border bg-surface/25"><div className="mx-auto max-w-5xl text-center"><Reveal><h2 className="text-balance text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Seu time vende. <span className="text-muted">A Morubi aprende.</span></h2><p className="mx-auto mt-5 max-w-2xl text-[17px] leading-7 text-muted">Cada call deixa de ser apenas uma conversa e passa a alimentar a inteligência comercial da sua empresa.</p></Reveal><div className="mt-12"><SystemFlow/></div></div></Section>}

export function LiveStory(){return <Section id="produto"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><div className="lg:sticky lg:top-28 lg:self-start"><SectionHeading eyebrow="Durante a call" title="Coaching no momento em que ele realmente importa." subtitle="A Morubi entende o contexto e mostra ao vendedor uma próxima ação — sem interromper a conversa e sem exigir um prompt."/><Link href="/live" className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-accent hover:brightness-110">Conhecer Morubi Live <ArrowRight size={14}/></Link></div><div className="space-y-5"><LiveCallDemo compact/><div className="grid gap-3 sm:grid-cols-3">{[["Buying signal","Como funciona a implantação?"],["Risco","Precisamos analisar internamente."],["Discovery","Impacto financeiro não quantificado."]].map(([title,text],i)=><Reveal key={title} delay={i*.08}><div className="h-full rounded-xl border border-white/[.07] bg-surface/45 p-4"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-accent">{title}</p><p className="mt-2 text-xs leading-5 text-subtle">“{text}”</p></div></Reveal>)}</div><div className="rounded-2xl border border-white/[.07] bg-surface/30 p-5"><p className="text-[10px] uppercase tracking-[.16em] text-muted">Uma conversa alimenta o sistema inteiro</p><div className="mt-4 grid grid-cols-[auto_1fr] gap-x-3 gap-y-4 text-xs"><StoryStep n="01" title="Cliente fala" text="A call vira contexto estruturado."/><StoryStep n="02" title="Morubi entende" text="Objeções, sinais e comportamentos são identificados."/><StoryStep n="03" title="Vendedor age" text="A orientação aparece no momento útil."/><StoryStep n="04" title="Operação aprende" text="A evidência chega à análise, ao gestor e ao playbook."/></div></div></div></div></Section>}
function StoryStep({n,title,text}:{n:string;title:string;text:string}){return <><span className="grid h-7 w-7 place-items-center rounded-full border border-accent/25 bg-accent/[.06] font-mono text-[9px] text-accent">{n}</span><div><p className="font-medium text-foreground">{title}</p><p className="mt-1 leading-5 text-muted">{text}</p></div></>}

export function ZeroPrompt(){return <Section><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><SectionHeading eyebrow="Zero prompt experience" title="Você não precisa perguntar à IA." subtitle="A Morubi entende quando ajudar. O vendedor mantém a atenção no cliente; o contexto aparece no fluxo da conversa."/><ZeroPromptComparison/></div></Section>}

export function Intelligence(){return <Section id="intelligence" className="border-y border-border bg-surface/20"><SectionHeading eyebrow="Depois da call" title={<>A call termina.<br/>A inteligência fica.</>} subtitle="Reveja a conversa sem assistir tudo de novo. Scores mostram onde olhar; evidências mostram por quê."/><div className="mt-12 grid gap-5 lg:grid-cols-[1.45fr_.55fr]"><CallScorePanel/><DealScorePanel/></div><div className="mt-6 text-right"><Link href="/intelligence" className="inline-flex items-center gap-2 text-sm text-accent">Explorar Intelligence <ArrowRight size={14}/></Link></div></Section>}

export function Manager(){return <Section id="gestores"><div className="mx-auto max-w-3xl text-center"><SectionHeading eyebrow="Morubi Manager" title="Uma visão que nenhum gestor conseguiria ter sozinho." subtitle="Acompanhe as interações comerciais sem transformar seu calendário em uma maratona de gravações." align="center"/></div><div className="mt-12"><ManagerDashboard/></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/[.08] bg-surface/55 p-5 sm:p-6"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-accent">O dashboard interpreta</p><h3 className="mt-3 text-xl font-semibold">Menos gráfico solto. Mais causa e próxima ação.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-muted">A Morubi conecta resultado, comportamento e trecho da conversa para que o gestor saiba onde intervir e o que desenvolver.</p><Link href="/manager" className="mt-5 inline-flex items-center gap-2 text-sm text-accent">Ver a experiência do gestor <ArrowRight size={14}/></Link></div><ReportPreview/></div></Section>}

export function Coaching(){return <Section id="vendedores" className="border-y border-border bg-surface/20"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><div><SectionHeading eyebrow="Morubi Coach" title="Cada vendedor recebe um treinador que conhece suas vendas." subtitle="O desenvolvimento parte do que aconteceu de verdade — e vira um próximo exercício claro."/><Link href="/coach" className="mt-6 inline-flex items-center gap-2 text-sm text-accent">Conhecer Morubi Coach <ArrowRight size={14}/></Link></div><CoachPanel/></div><div className="mt-16 grid gap-4 lg:grid-cols-2"><RoleplayCard/><RampCard/></div></Section>}

function RoleplayCard(){return <div className="rounded-2xl border border-white/[.08] bg-surface/65 p-5 sm:p-6"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[.16em] text-accent">AI Roleplay · conceito</span><MessageSquareText size={16} className="text-muted"/></div><h3 className="mt-5 text-xl font-semibold">Treine com os erros das suas próprias calls.</h3><p className="mt-3 text-sm leading-6 text-muted">Cenário: cliente interessado com forte objeção de preço.</p><div className="mt-5 rounded-xl border border-white/[.07] bg-white/[.02] p-4"><p className="text-xs text-subtle">Objetivo</p><p className="mt-1 text-sm">Defender valor sem conceder desconto cedo.</p><div className="mt-4 flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs text-muted">Dificuldade · ●●●●○</span><button className="w-full rounded-lg bg-accent px-4 py-2 text-xs font-semibold text-accent-foreground sm:w-auto">Começar simulação</button></div></div></div>}
function RampCard(){return <div className="rounded-2xl border border-white/[.08] bg-surface/65 p-5 sm:p-6"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[.16em] text-accent">Ramp Mode · conceito</span><Gauge size={16} className="text-muted"/></div><h3 className="mt-5 text-xl font-semibold">Novos vendedores não precisam aprender sozinhos.</h3><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-sm font-medium">João Martins</p><p className="text-xs text-muted">Dia 18 de onboarding</p></div><p className="shrink-0 text-3xl font-semibold">78<span className="text-sm text-muted">%</span></p></div><div className="mt-4 h-1.5 rounded-full bg-white/[.06]"><div className="h-full w-[78%] rounded-full bg-accent"/></div><div className="mt-5 flex flex-wrap items-center justify-center gap-2 text-[10px] text-muted"><span className="text-foreground">Ramp Mode</span><ArrowRight size={11}/><span>Assisted</span><ArrowRight size={11}/><span>Expert</span></div></div>}

export function Playbook(){return <Section><div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-20"><div><SectionHeading eyebrow="Playbook da empresa" title={<>A Morubi não vende como a internet ensina. <span className="text-muted">Ela vende como sua empresa vende.</span></>} subtitle="Conhecimento geral, contexto da empresa e evidências da própria operação em uma mesma camada de orientação."/><div className="mt-8 grid grid-cols-2 gap-2">{[["01","Sales Intelligence"],["02","Company Playbook"],["03","Deal Context"],["04","Learned Behavior"]].map(([n,t])=><div key={n} className="rounded-xl border border-white/[.07] bg-white/[.02] p-3"><p className="font-mono text-[9px] text-accent">{n}</p><p className="mt-2 text-xs text-subtle">{t}</p></div>)}</div></div><PlaybookPanel/></div><div className="mt-20 rounded-3xl border border-accent/20 bg-accent/[.035] p-6 sm:p-10"><div className="grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-[10px] uppercase tracking-[.16em] text-accent">Playbook vivo · visão de produto</span><h3 className="mt-3 text-2xl font-semibold">Um playbook que aprende com quem realmente compra.</h3><p className="mt-3 text-sm leading-6 text-muted">Calls viram resultados; resultados revelam padrões; o gestor decide o que volta ao playbook.</p></div><div><SystemFlow/><div className="mt-5 rounded-xl border border-white/[.08] bg-bg/50 p-4"><p className="text-[10px] uppercase tracking-wider text-accent">Padrão identificado</p><p className="mt-2 text-sm leading-6 text-subtle">Em oportunidades Enterprise, confirmar o processo decisório antes da demonstração aparece associado ao avanço para a próxima etapa.</p><button className="mt-4 text-xs font-medium text-accent">Adicionar insight ao playbook →</button></div></div></div></div></Section>}

const integrations=[{title:"Meetings",items:[["Google Meet","Planejada"],["Microsoft Teams","Planejada"],["Zoom","Planejada"]]},{title:"CRM",items:[["HubSpot","Planejada"],["Salesforce","Planejada"],["Pipedrive","Planejada"],["Kommo","Planejada"]]},{title:"Communication",items:[["WhatsApp","Disponível"]]}];
export function Integrations(){return <Section id="integracoes" className="border-y border-border bg-surface/20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-20"><SectionHeading eyebrow="Integrações" title="A inteligência acompanha sua operação." subtitle="Suas ferramentas registram as interações. A Morubi conecta os pontos — com disponibilidade e roadmap sempre identificados."/><div className="grid gap-3 sm:grid-cols-3">{integrations.map(group=><div key={group.title} className="rounded-2xl border border-white/[.07] bg-surface/55 p-5"><p className="text-xs font-medium">{group.title}</p><div className="mt-4 space-y-2">{group.items.map(([name,status])=><button key={name} onClick={()=>track("integration_click",{integration:name})} className="flex w-full items-center justify-between rounded-lg border border-white/[.06] bg-white/[.02] px-3 py-2.5 text-left"><span className="text-xs text-subtle">{name}</span><span className={status==="Disponível"?"text-[9px] text-positive":"text-[9px] text-muted"}>{status}</span></button>)}</div></div>)}</div></div></Section>}

export function HowAndTrust(){return <><Section id="como-funciona"><SectionHeading eyebrow="Como funciona" title="Da experiência do time ao aprendizado da operação." align="center" className="mx-auto"/><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{[[Layers3,"01","Conectamos o conhecimento","Playbook, produto, ICP, objeções e processo."],[Headphones,"02","Morubi acompanha","Interações são transformadas em contexto."],[Sparkles,"03","Morubi orienta","Inteligência aparece nos momentos críticos."],[Workflow,"04","Sua operação aprende","Gestores descobrem padrões e desenvolvem o time."]].map(([Icon,n,title,text],i)=>{const I=Icon as typeof Layers3;return <Reveal key={String(n)} delay={i*.06}><div className="h-full rounded-2xl border border-white/[.07] bg-surface/45 p-5"><div className="flex items-center justify-between"><I size={17} className="text-accent"/><span className="font-mono text-[10px] text-muted">{n as string}</span></div><p className="mt-6 text-sm font-medium">{title as string}</p><p className="mt-2 text-xs leading-5 text-muted">{text as string}</p></div></Reveal>})}</div></Section><Section id="seguranca" className="border-y border-border bg-surface/20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-20"><div><SectionHeading eyebrow="Segurança e privacidade" title="Inteligência comercial exige confiança." subtitle="A arquitetura e as políticas precisam acompanhar a sensibilidade das conversas comerciais — sem promessas vagas ou selos não verificados."/><Link href="/seguranca" className="mt-6 inline-flex items-center gap-2 text-sm text-accent">Ver princípios de segurança <ArrowRight size={14}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{[[LockKeyhole,"Dados protegidos","Arquitetura preparada para proteger informações comerciais."],[Users,"Controle da empresa","Permissões e acesso definidos pela operação."],[ShieldCheck,"Privacidade","Tratamento responsável das conversas analisadas."],[BookOpenCheck,"LGPD","Estrutura documental para explicar papéis e direitos."]].map(([Icon,title,text])=>{const I=Icon as typeof LockKeyhole;return <div key={title as string} className="rounded-xl border border-white/[.07] bg-surface/55 p-5"><I size={17} className="text-accent"/><p className="mt-4 text-sm font-medium">{title as string}</p><p className="mt-2 text-xs leading-5 text-muted">{text as string}</p></div>})}</div></div></Section></>}

export function OutcomesPricing(){return <><Section><SectionHeading eyebrow="Impacto operacional" title="Construído para melhorar o que realmente move vendas." align="center" className="mx-auto"/><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[MessageSquareText,"Mais contexto","O vendedor sabe como agir em momentos críticos."],[BarChart3,"Mais visibilidade","O gestor entende o que acontece nas calls."],[BrainCircuit,"Mais aprendizado","Interações se transformam em inteligência."],[CircleCheck,"Mais consistência","O playbook deixa de depender da memória."]].map(([Icon,t,d])=>{const I=Icon as typeof MessageSquareText;return <div key={t as string} className="rounded-2xl border border-white/[.07] bg-surface/45 p-5"><I size={17} className="text-accent"/><p className="mt-4 text-sm font-medium">{t as string}</p><p className="mt-2 text-xs leading-5 text-muted">{d as string}</p></div>})}</div></Section><Section id="precos" className="border-y border-border bg-surface/20"><div className="mx-auto max-w-4xl"><SectionHeading eyebrow="Planos" title="Inteligência para a operação inteira — não mais uma ferramenta individual." align="center" className="mx-auto"/><div className="mt-12 overflow-hidden rounded-3xl border border-accent/25 bg-surface/70"><div className="grid lg:grid-cols-[1fr_.8fr]"><div className="p-6 sm:p-9"><p className="text-sm font-medium text-accent">Morubi Teams</p><div className="mt-4 flex items-end gap-2"><span className="text-sm text-muted">A partir de</span><strong className="text-4xl tracking-[-.04em]">R$ 997</strong><span className="mb-1 text-sm text-muted">/mês</span></div><p className="mt-4 text-sm leading-6 text-muted">Para equipes que querem transformar cada call em inteligência. Escopo final depende dos módulos disponíveis e do uso da equipe.</p><ScheduleButton event="pricing_demo_click" className="mt-7"/></div><div className="border-t border-white/[.07] bg-white/[.018] p-6 lg:border-l lg:border-t-0 sm:p-9"><p className="text-xs font-medium">Configuração dimensionada para sua operação</p><ul className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{["Playbook personalizado","Análise pós-call","Dashboard gerencial","Coaching individual","Insights da equipe","Relatórios automáticos"].map(x=><li key={x} className="flex gap-2 text-xs text-subtle"><Check size={13} className="text-positive"/>{x}</li>)}</ul><p className="mt-6 text-[11px] leading-5 text-muted">Módulos em desenvolvimento ou roadmap são validados durante a demonstração.</p></div></div><div className="flex flex-col justify-between gap-3 border-t border-white/[.07] px-6 py-4 text-xs sm:flex-row sm:items-center"><span className="text-muted">Precisa de uma operação maior? <strong className="text-foreground">Morubi Enterprise</strong></span><Link href="/contato" className="text-accent">Conversar com vendas →</Link></div></div></div></Section></>}

const faqs=[
  ["A Morubi substitui meu CRM?","Não. A Morubi funciona como uma camada de inteligência sobre a operação comercial."],
  ["A Morubi substitui o gestor comercial?","Não. Ela amplia a capacidade de acompanhar, diagnosticar e desenvolver o time."],
  ["O vendedor precisa perguntar algo para a IA durante a call?","A experiência projetada identifica momentos relevantes e apresenta orientação contextual. A disponibilidade é confirmada na demonstração."],
  ["A Morubi funciona durante reuniões?","O suporte depende das integrações e dos ambientes habilitados para cada operação. O roadmap é apresentado com transparência."],
  ["Posso usar o playbook da minha empresa?","Sim. A configuração do contexto e do playbook faz parte do onboarding."],
  ["A Morubi grava as reuniões?","O comportamento depende do ambiente e da configuração adotada. Informamos o fluxo de captura, consentimento e retenção antes da implantação."],
  ["Como meus dados são tratados?","A empresa controla o acesso e o contexto comercial. Os detalhes de tratamento, papéis e direitos estão na Política de Privacidade."],
  ["Funciona com meu CRM?","As conexões disponíveis são validadas na demonstração. Integrações planejadas aparecem separadas das disponíveis."],
  ["Existe implantação?","Sim. O onboarding inclui a configuração do contexto comercial e do playbook da operação."],
] as const;
export function NewFaq(){const[open,setOpen]=React.useState(0);return <Section id="faq"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:gap-20"><SectionHeading eyebrow="Perguntas frequentes" title="Clareza antes da implantação." subtitle="Sem promessas escondidas em letra pequena."/><div className="border-t border-border">{faqs.map(([q,a],i)=><div key={q} className="border-b border-border"><button onClick={()=>{setOpen(open===i?-1:i);track("faq_opened",{question:q})}} className="flex w-full items-center justify-between gap-5 py-5 text-left" aria-expanded={open===i}><span className="text-sm font-medium sm:text-[15px]">{q}</span><ChevronDown size={16} className={`shrink-0 text-muted transition ${open===i?"rotate-180":""}`}/></button><AnimatePresence initial={false}>{open===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><p className="max-w-2xl pb-5 text-sm leading-6 text-muted">{a}</p></motion.div>}</AnimatePresence></div>)}</div></div></Section>}

export function FinalCta(){return <section className="relative overflow-hidden py-28 sm:py-36"><div className="pointer-events-none absolute inset-0 bg-grid opacity-40"/><div className="pointer-events-none absolute left-1/2 top-1/2 h-[420px] w-[760px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-accent/[.09] blur-[120px]"/><div className="relative mx-auto max-w-4xl px-6 text-center"><Eyebrow>Morubi</Eyebrow><h2 className="mt-6 text-balance text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Seu time já está tendo centenas de conversas. <span className="text-muted">Comece a aprender com todas elas.</span></h2><p className="mx-auto mt-6 max-w-xl text-[17px] leading-7 text-muted">Inteligência durante a venda. Clareza depois dela. Evolução em cada próxima conversa.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><ScheduleButton event="final_cta_click"/><DemoLink event="final_cta_click"/></div></div></section>}
