import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import { ArrowRight, CircleDot } from "lucide-react";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/sections/footer";
import { DemoLink, ScheduleButton } from "@/components/tracked-actions";
import { Eyebrow } from "@/components/ui/primitives";

export function SolutionPage({ eyebrow, title, description, children, capabilities, steps, note }: { eyebrow:string; title:string; description:string; children:React.ReactNode; capabilities:{title:string;text:string;icon:LucideIcon}[]; steps?:string[]; note?:string }){
  return <><Navbar/><main><section className="relative overflow-hidden pb-20 pt-36 sm:pb-28 sm:pt-44"><div className="pointer-events-none absolute inset-0 bg-grid opacity-50"/><div className="aurora pointer-events-none absolute left-1/2 top-[-350px] h-[700px] w-[1000px] -translate-x-1/2 rounded-full"/><div className="relative mx-auto max-w-8xl px-6 lg:px-8"><div className="grid items-center gap-14 lg:grid-cols-[.78fr_1.22fr]"><div><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-6 text-balance text-[42px] font-semibold leading-[1.04] tracking-[-.045em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-xl text-[17px] leading-7 text-muted">{description}</p>{note&&<p className="mt-4 flex gap-2 text-xs leading-5 text-muted"><CircleDot size={13} className="mt-1 shrink-0 text-accent"/>{note}</p>}<div className="mt-8 flex flex-col gap-3 sm:flex-row"><DemoLink/><ScheduleButton/></div></div><div>{children}</div></div></div></section><section className="border-y border-border bg-surface/20 py-20 sm:py-28"><div className="mx-auto max-w-8xl px-6 lg:px-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{capabilities.map(({title,text,icon:Icon})=><div key={title} className="rounded-2xl border border-white/[.07] bg-surface/55 p-5"><Icon size={17} className="text-accent"/><h2 className="mt-5 text-sm font-medium">{title}</h2><p className="mt-2 text-xs leading-5 text-muted">{text}</p></div>)}</div></div></section>{steps&&<section className="py-20 sm:py-28"><div className="mx-auto max-w-4xl px-6"><Eyebrow>Como funciona</Eyebrow><h2 className="mt-5 text-3xl font-semibold tracking-tight">Do contexto à próxima ação.</h2><div className="mt-10 space-y-3">{steps.map((s,i)=><div key={s} className="flex gap-4 rounded-xl border border-white/[.07] bg-surface/35 p-4"><span className="font-mono text-[10px] text-accent">0{i+1}</span><p className="text-sm text-subtle">{s}</p></div>)}</div><div className="mt-8"><Link href="/#como-funciona" className="inline-flex items-center gap-2 text-sm text-accent">Ver o sistema completo <ArrowRight size={14}/></Link></div></div></section>}</main><Footer/></>
}
